version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "21:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.440.4
    - 1.440.5
    - 1.445.0
    - 1.446.0
    - 1.447.0
    - 1.448.0
    - 1.450.0
    - 1.452.0
    - 1.454.0
    - 1.455.0
    - 1.456.0
    - 1.457.0
    - 1.458.0
    - 1.459.0
    - 1.460.0
    - 1.461.0
    - 1.464.0
    - 1.467.0
    - 1.471.0
    - 1.473.0
    - 1.476.0
    - 1.478.0
    - 1.483.0
    - 1.485.0
    - 1.488.0
    - 1.491.0
    - 1.495.0
    - 1.500.0
    - 1.502.0
    - 1.505.0
    - 1.509.0
    - 1.511.0
    - 1.514.0
    - 1.517.0
    - 1.520.0
    - 1.521.0
    - 1.522.0
    - 1.526.0
    - 1.528.0
    - 1.529.0
    - 1.530.0
    - 1.532.0
    - 1.538.0
    - 1.541.0
    - 1.563.0
    - 1.566.0
    - 1.570.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.14
    - 4.2.15
    - 4.2.16
  - dependency-name: ali-oss
    versions:
    - 6.13.2
    - 6.14.0
    - 6.14.1
    - 6.15.0
  - dependency-name: mocha
    versions:
    - 8.2.1
    - 8.3.0
    - 8.3.1
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
    - 8.2.1
  - dependency-name: imagemin-pngquant
    versions:
    - 9.0.1
